package com.as400datamigration.audit;

public enum TableStatus {
	
	TABLE_NOT_CREATED,
	
	TABLE_NOT_FOUND_AT_SOURCE,
	TABLE_DESC_NOT_FOUND_AT_SOURCE,
	TABLE_CREATION_FAILED,
	
	TABLE_CREATED_WITH_NO_DATA,
	MIGRATION_PROCESS_IN_RUNNING,
	
	MIGRATION_SUCCESSFUL, 
	MIGRATION_FAILED,
	
	MIGRATION_SYNC_SUCCESSFUL, 
	MIGRATION_SYNC_FAIL  

}
